global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "story_validator"
    static_configs:
      - targets: ['127.0.0.1:26660']  # Tendermint's Prometheus metrics endpoint
        labels:
          deployment: production
          chain: STORY
          network: testnet
          servicetype: validator
          cloud: yourcloud
          region: yourregion
          purpose: Cosmos
    metrics_path: '/metrics'  

  - job_name: 'node_exporter'  
    static_configs:
      - targets: ['localhost:9100'] 