global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "story-validator"
    static_configs:
    - targets: ["127.0.0.1:26660", "127.0.0.1:9100", "127.0.0.1:30303"]
    labels:
      deployment: production
      chain: STORY
      network: testnet
      servicetype: validator
      purpose: Cosmos
      metrics_path: '/metrics' 
